# Nagara Tunnel Lite
APP_NAME="Nagara Tunnel Lite"
APP_VERSION="2.1.0"

APP_DIR="/opt/nagara-tunnel-lite"
LOG_DIR="/var/log/nagara-tunnel-lite"

DOMAIN=""
NGINX_ENABLED="true"
SSL_ENABLED="false"
XRAY_ENABLED="true"
HAPROXY_ENABLED="true"
DROPBEAR_ENABLED="true"
FAIL2BAN_ENABLED="true"

VMESS_ENABLED="true"
VLESS_ENABLED="true"
TROJAN_ENABLED="true"
