# Nagara Tunnel Lite
APP_NAME="Nagara Tunnel Lite"
APP_VERSION="2.0.0"

APP_DIR="/opt/nagara-tunnel-lite"
LOG_DIR="/var/log/nagara-tunnel-lite"

XRAY_ENABLED="false"
NGINX_ENABLED="false"
SSL_ENABLED="false"
HAPROXY_ENABLED="false"
DROPBEAR_ENABLED="false"

DOMAIN=""
SSL_EMAIL=""

VMESS_ENABLED="true"
VLESS_ENABLED="true"
TROJAN_ENABLED="true"
